import { ComplexFormStatics, FormStatics } from "@/types/statics/forms";
import { CreateOutgoingInput, MovementDto, UpdateOutgoingInput } from "../_interfaces/outgoing.interface";

export const FORMSTATICS: ComplexFormStatics<CreateOutgoingInput, MovementDto> = {
    name: {
        required: true,
        label: "Nombre",
        type: "text",
        placeholder: "Egreso de insumo, reducción de stock, etc.",
        name: "name",
    },
    description: {
        required: false,
        label: "Descripción",
        defaultValue: "",
        type: "text",
        placeholder: "Descripción",
        name: "description",
    },
    storageId: {
        required: true,
        label: "Almacenamiento",
        defaultValue: "",
        type: "select",
        placeholder: "Selecciona un almacenamiento",
        emptyMessage: "No se encontraron almacenes",
        name: "storageId",
    },
    date: {
        required: true,
        label: "Fecha",
        defaultValue: new Date().toISOString().split("T")[0],
        type: "date",
        placeholder: "Fecha",
        name: "date",
    },
    state: {
        required: false,
        label: "Estado de consumación de egreso",
        defaultValue: undefined,
        type: "checkbox",
        placeholder: "Estado",
        name: "state",
    },
    referenceId: {
        required: false,
        label: "Referencia",
        defaultValue: "",
        type: "text",
        placeholder: "Referencia",
        name: "referenceId",
    },
    movement: {
        required: true,
        label: "Movimientos",
        type: "array",
        placeholder: "Movimientos",
        name: "movement",
        subFields: {
            productId: {
                required: true,
                label: "Producto",
                defaultValue: "",
                type: "select",
                placeholder: "Selecciona un producto",
                emptyMessage: "No se encontraron productos",
                name: "productId",
            },
            quantity: {
                required: true,
                label: "Cantidad",
                defaultValue: 0,
                type: "number",
                placeholder: "Cantidad",
                name: "quantity",
            },
            date: {
                required: false,
                label: "Fecha",
                defaultValue: undefined,//new Date().toISOString().split("T")[0],
                type: "date",
                placeholder: "Fecha",
                name: "date",
            },
            state: {
                required: false,
                label: "Estado",
                defaultValue: "false",
                type: "checkbox",
                placeholder: "Estado",
                name: "state",
            },
        },
    },
}

export const UPDATEFORMSTATICS: FormStatics<UpdateOutgoingInput> = {
    name: {
        required: false,
        label: "Nombre",
        type: "text",
        defaultValue: "",
        placeholder: "Egreso de insumo, reducción de stock, etc.",
        name: "name",
    },
    description: {
        required: false,
        label: "Descripción",
        defaultValue: "",
        type: "text",
        placeholder: "Descripción",
        name: "description",
    },
    storageId: {
        required: false,
        label: "Almacenamiento",
        defaultValue: "",
        type: "select",
        placeholder: "Selecciona un almacenamiento",
        emptyMessage: "No se encontraron almacenes",
        name: "storageId",
    },
    date: {
        required: false,
        label: "Fecha",
        defaultValue: undefined,
        type: "date",
        placeholder: "Fecha",
        name: "date",
    },
    state: {
        required: false,
        label: "Estado de consumación de egreso",
        defaultValue: undefined,
        type: "checkbox",
        placeholder: "Estado",
        name: "state",
    },
    referenceId: {
        required: false,
        label: "Referencia",
        defaultValue: "",
        type: "text",
        placeholder: "Referencia",
        name: "referenceId",
    },
}