import { ComplexFormStatics } from "@/types/statics/forms";
import { CreateOutgoingInput, MovementDto, UpdateOutgoingStorageInput, UpdateOutgoingStorageMovementDto } from "../_interfaces/outgoing.interface";

export const FORMSTATICS: ComplexFormStatics<CreateOutgoingInput, MovementDto> = {
    name: {
        required: true,
        label: "Nombre",
        type: "text",
        placeholder: "Egreso de insumo, reducción de stock, etc.",
        name: "name",
    },
    description: {
        required: false,
        label: "Descripción",
        defaultValue: "",
        type: "text",
        placeholder: "Descripción",
        name: "description",
    },
    storageId: {
        required: true,
        label: "Almacén de origen",
        defaultValue: "",
        type: "select",
        placeholder: "Selecciona un almacén",
        emptyMessage: "No se encontraron almacenes",
        name: "storageId",
    },
    date: {
        required: true,
        label: "Fecha",
        defaultValue: new Date().toISOString().split("T")[0],
        type: "date",
        placeholder: "Fecha",
        name: "date",
    },
    state: {
        required: false,
        label: "Estado de consumación de egreso",
        defaultValue: undefined,
        type: "checkbox",
        placeholder: "Estado",
        name: "state",
    },
    isTransference:{
        required: false,
        label: "¿Es una transferencia?",
        defaultValue: false,
        type: "checkbox",
        placeholder: "Transferencia",
        name: "isTransference",
        description: "Si es una transferencia, se debe seleccionar el almacenamiento de destino",
    },
    referenceId: {
        required: false,
        label: "Almacén de destino",
        defaultValue: "",
        type: "text",
        placeholder: "Selecciona un almacén",
        emptyMessage: "No se encontraron más almacenes. Cree más almacenes.",
        name: "referenceId",
    },
    movement: {
        required: true,
        label: "Movimientos",
        type: "array",
        placeholder: "Movimientos",
        name: "movement",
        subFields: {
            productId: {
                required: true,
                label: "Producto",
                defaultValue: "",
                type: "select",
                placeholder: "Selecciona un producto",
                emptyMessage: "No se encontraron productos",
                name: "productId",
            },
            quantity: {
                required: true,
                label: "Cantidad",
                defaultValue: 0,
                type: "number",
                placeholder: "Cantidad",
                name: "quantity",
            },
            buyingPrice: {
                required: false,
                label: "Precio de compra",
                defaultValue: 0,
                type: "number",
                placeholder: "Precio de compra",
                name: "buyingPrice",
            },
            date: {
                required: false,
                label: "Fecha",
                defaultValue: undefined,//new Date().toISOString().split("T")[0],
                type: "date",
                placeholder: "Fecha",
                name: "date",
            },
            state: {
                required: false,
                label: "Estado",
                defaultValue: "false",
                type: "checkbox",
                placeholder: "Estado",
                name: "state",
            },
        },
    },
}

export const UPDATEFORMSTATICS: ComplexFormStatics<UpdateOutgoingStorageInput, UpdateOutgoingStorageMovementDto> = {
    name: {
        required: false,
        label: "Nombre",
        type: "text",
        defaultValue: "",
        placeholder: "Egreso de insumo, reducción de stock, etc.",
        name: "name",
    },
    description: {
        required: false,
        label: "Descripción",
        defaultValue: "",
        type: "text",
        placeholder: "Descripción",
        name: "description",
    },
    storageId: {
        required: false,
        label: "Almacén de origen",
        defaultValue: "",
        type: "select",
        placeholder: "Selecciona un almacén",
        emptyMessage: "No se encontraron almacenes",
        name: "storageId",
    },
    date: {
        required: false,
        label: "Fecha",
        defaultValue: undefined,
        type: "date",
        placeholder: "Fecha",
        name: "date",
    },
    state: {
        required: false,
        label: "Estado de consumación de egreso",
        defaultValue: undefined,
        type: "checkbox",
        placeholder: "Estado",
        name: "state",
    },
    isTransference:{
        required: false,
        label: "¿Es una transferencia?",
        defaultValue: false,
        type: "checkbox",
        placeholder: "Transferencia",
        name: "isTransference",
        description: "Si es una transferencia, se debe seleccionar el almacenamiento de destino",
    },
    referenceId: {
        required: false,
        label: "Almacén de destino",
        defaultValue: "",
        type: "text",
        placeholder: "Selecciona un almacén",
        emptyMessage: "No se encontraron almacenes",
        name: "referenceId",
    },
    movement: {
        required: true,
        label: "Movimientos",
        type: "array",
        placeholder: "Movimientos",
        name: "movement",
        subFields: {
            id: {
                required: true,
                label: "ID",
                defaultValue: "",
                type: "text",
                placeholder: "ID",
                name: "id",
            },
            productId: {
                required: false,
                label: "Producto",
                defaultValue: "",
                type: "select",
                placeholder: "Selecciona un producto",
                emptyMessage: "No se encontraron productos",
                name: "productId",
            },
            quantity: {
                required: true,
                label: "Cantidad",
                defaultValue: 1,
                type: "number",
                placeholder: "Cantidad",
                name: "quantity",
            },
            buyingPrice: {
                required: false,
                label: "Precio de compra",
                defaultValue: 0,
                type: "number",
                placeholder: "Precio de compra",
                name: "buyingPrice",
            },
            date: {
                required: false,
                label: "Fecha",
                defaultValue: undefined,//new Date().toISOString().split("T")[0],
                type: "date",
                placeholder: "Fecha",
                name: "date",
            },
            state: {
                required: false,
                label: "Estado",
                defaultValue: "false",
                type: "checkbox",
                placeholder: "Estado",
                name: "state",
            },
        },
    },
}