// import { FormStatics } from "@/types/statics/forms";
// import { CreateOrderInput, UpdateOrderInput, } from "../_interfaces/order.interface";

import { ComplexFormStatics } from "@/types/statics/forms";
import { CreateProductSaleBillingInput, ProductSaleItemDto } from "../../orders/_interfaces/order.interface";

// // export const createOrderSchema = z.object({
// //     code: z.string().optional(),
// //     type: z.enum(["MEDICAL_PRESCRIPTION_ORDER", "MEDICAL_CONSULTATION_ORDER", "PRODUCT_SALE_ORDER", "PRODUCT_PURCHASE_ORDER"]),
// //     movementTypeId: z.string(),
// //     referenceId: z.string(),
// //     sourceId: z.string().optional(), //Es la referencia al storage
// //     targetId: z.string().optional(),
// //     status: z.enum(["DRAFT", "PENDING", "PROCESSING", "COMPLETED", "CANCELLED", "REFUNDED", "REQUIRES_ATTENTION"]),
// //     currency: z.string(),
// //     subtotal: z.number(),
// //     tax: z.number(),
// //     total: z.number(),
// //     notes: z.string().optional(),
// //     metadata: z.record(z.never()).optional(),
// //   }) satisfies z.ZodType<CreateOrderDto>;

// export const FORMSTATICS: FormStatics<CreateOrderInput> = {
//     code: {
//         required: false,
//         label: "Código",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Código de la orden",
//         name: "code",
//     },
//     type: {
//         required: true,
//         label: "Tipo",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Tipo de orden",
//         name: "type",
//     },
//     movementTypeId: {
//         required: true,
//         label: "Tipo de movimiento",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Tipo de movimiento",
//         name: "movementTypeId",
//     },
//     referenceId: {
//         required: true,
//         label: "Referencia",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Referencia de la orden",
//         name: "referenceId",
//     },
//     sourceId: {
//         required: false,
//         label: "Almacén de origen",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Almacén de origen",
//         name: "sourceId",
//     },
//     targetId: {
//         required: false,
//         label: "Almacén de destino",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Almacén de destino",
//         name: "targetId",
//     },
//     status: {
//         required: true,
//         label: "Estado",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Estado de la orden",
//         name: "status",
//     },
//     currency: {
//         required: true,
//         label: "Moneda",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Moneda de la orden",
//         name: "currency",
//     },
//     subtotal: {
//         required: true,
//         label: "Subtotal",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Subtotal de la orden",
//         name: "subtotal",
//     },
//     tax: {
//         required: true,
//         label: "Impuesto",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Impuesto de la orden",
//         name: "tax",
//     },
//     total: {
//         required: true,
//         label: "Total",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Total de la orden",
//         name: "total",
//     },
//     notes: {
//         required: false,
//         label: "Notas",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Notas de la orden",
//         name: "notes",
//     },
//     metadata: {
//         required: false,
//         label: "Metadatos",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Metadatos de la orden",
//         name: "metadata",
//     },
// }

// // export const updateOrderSchema = z.object({
// //     code: z.string().optional(),
// //     type: z.enum(["MEDICAL_PRESCRIPTION_ORDER", "MEDICAL_CONSULTATION_ORDER", "PRODUCT_SALE_ORDER", "PRODUCT_PURCHASE_ORDER"]).optional(),
// //     movementTypeId: z.string().optional(),
// //     referenceId: z.string().optional(),
// //     sourceId: z.string().optional(),
// //     targetId: z.string().optional(),
// //     status: z.enum(["DRAFT", "PENDING", "PROCESSING", "COMPLETED", "CANCELLED", "REFUNDED", "REQUIRES_ATTENTION"]).optional(),
// //     currency: z.string().optional(),
// //     subtotal: z.number().optional(),
// //     tax: z.number().optional(),
// //     total: z.number().optional(),
// //     notes: z.string().optional(),
// //     metadata: z.record(z.never()).optional(),
// //   }) satisfies z.ZodType<UpdateOrderDto>;

// export const UPDATEFORMSTATICS: FormStatics<UpdateOrderInput> = {
//     code: {
//         required: false,
//         label: "Código",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Código de la orden",
//         name: "code",
//     },
//     type: {
//         required: false,
//         label: "Tipo",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Tipo de orden",
//         name: "type",
//     },
//     movementTypeId: {
//         required: false,
//         label: "Tipo de movimiento",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Tipo de movimiento",
//         name: "movementTypeId",
//     },
//     referenceId: {
//         required: false,
//         label: "Referencia",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Referencia de la orden",
//         name: "referenceId",
//     },
//     sourceId: {
//         required: false,
//         label: "Almacén de origen",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Almacén de origen",
//         name: "sourceId",
//     },
//     targetId: {
//         required: false,
//         label: "Almacén de destino",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Almacén de destino",
//         name: "targetId",
//     },
//     status: {
//         required: false,
//         label: "Estado",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Estado de la orden",
//         name: "status",
//     },
//     currency: {
//         required: false,
//         label: "Moneda",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Moneda de la orden",
//         name: "currency",
//     },
//     subtotal: {
//         required: false,
//         label: "Subtotal",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Subtotal de la orden",
//         name: "subtotal",
//     },
//     tax: {
//         required: false,
//         label: "Impuesto",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Impuesto de la orden",
//         name: "tax",
//     },
//     total: {
//         required: false,
//         label: "Total",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Total de la orden",
//         name: "total",
//     },
//     notes: {
//         required: false,
//         label: "Notas",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Notas de la orden",
//         name: "notes",
//     },
//     metadata: {
//         required: false,
//         label: "Metadatos",
//         defaultValue: "",
//         type: "text",
//         placeholder: "Metadatos de la orden",
//         name: "metadata",
//     },
// }

// export const createProductSaleBillingSchema = z.object({
//   products: z.array(z.object({
//     productId: z.string(),
//     quantity: z.number(),
//   })),
//   storageId: z.string(),
//   branchId: z.string(),
//   storageLocation: z.string().optional(),
//   batchNumber: z.string().optional(),
//   referenceId: z.string().optional(),
//   currency: z.string(),
//   paymentMethod: z.enum(["CASH", "BANK_TRANSFER", "YAPE"]),
//   notes: z.string().optional(),
//   metadata: z.record(z.never()).optional(),
// }) satisfies z.ZodType<CreateProductSaleBillingDto>;
//export type CreateProductSaleBillingInput = z.infer<typeof createProductSaleBillingSchema>;

//Faltan lo de los servicios
export const CREATE_PRESCRIPTION_ORDER_FORMSTATICS: ComplexFormStatics<CreateProductSaleBillingInput, ProductSaleItemDto> = {
    products: {
        required: true,
        label: "Productos",
        type: "array",
        subFields:{
            productId: {
                required: true,
                label: "Producto",
                defaultValue: undefined,
                type: "select",
                placeholder: "Selecciona un producto",
                emptyMessage: "No se encontraron productos",
                name: "productId",
            },
            quantity: {
                required: true,
                label: "Cantidad",
                defaultValue: 0,
                type: "number",
                placeholder: "Cantidad",
                name: "quantity",
            },
        },
        placeholder: "Productos de la orden",
        name: "products",
    },
    storageId: {
        required: true,
        label: "Almacén de origen",
        defaultValue: undefined,
        type: "text",
        placeholder: "Almacén de origen del producto",
        name: "storageId",
    },
    branchId: {
        required: true,
        label: "Sucursal de la venta",
        defaultValue: undefined,
        type: "text",
        placeholder: "Sucursal que genera la orden",
        name: "branchId",
    },
    storageLocation: {
        required: false,
        label: "Ubicación de almacenamiento",
        defaultValue: undefined,
        type: "text",
        placeholder: "Ubicación de almacenamiento de la orden",
        name: "storageLocation",
    },
    batchNumber: {
        required: false,
        label: "Número de lote",
        defaultValue: undefined,
        type: "text",
        placeholder: "Número de lote de la orden",
        name: "batchNumber",
    },
    referenceId: {
        required: false,
        label: "Referencia",
        defaultValue: undefined,
        type: "text",
        placeholder: "Referencia de la orden",
        name: "referenceId",
    },
    currency: {
        required: true,
        label: "Moneda",
        defaultValue: undefined,
        type: "text",
        placeholder: "Moneda de la orden",
        name: "currency",
    },
    paymentMethod: {
        required: true,
        label: "Método de pago",
        defaultValue: undefined,
        type: "text",
        placeholder: "Método de pago de la orden",
        name: "paymentMethod",
    },
    notes: {
        required: false,
        label: "Notas",
        defaultValue: undefined,
        type: "text",
        placeholder: "Notas de la orden",
        name: "notes",
    },
    metadata: {
        required: false,
        label: "Metadatos",
        defaultValue: undefined,
        type: "text",
        placeholder: "Metadatos de la orden",
        name: "metadata",
    },
}