import { FormStatics } from "@/types/statics/forms";
import {
  CreatePatientInput,
  UpdatePatientInput,
} from "../_interfaces/patient.interface";

export const FORMSTATICS: FormStatics<CreatePatientInput> = {
  name: {
    required: true,
    label: "Nombre",
    type: "text",
    placeholder: "Nombre del paciente",
    name: "name",
    defaultValue: "",
  },
  lastName: {
    required: false,
    label: "Apellido",
    type: "text",
    placeholder: "Apellido del paciente",
    name: "lastName",
    defaultValue: "",
  },
  dni: {
    required: true,
    label: "DNI",
    type: "number",
    placeholder: "DNI del paciente",
    name: "dni",
    defaultValue: "",
  },
  birthDate: {
    required: false,
    label: "Fecha de Nacimiento",
    type: "date",
    placeholder: "Fecha de nacimiento del paciente",
    name: "birthDate",
    defaultValue: "",
  },
  gender: {
    required: true,
    label: "Género",
    type: "text",
    placeholder: "Género del paciente",
    name: "gender",
    defaultValue: "",
  },
  address: {
    required: false,
    label: "Dirección",
    type: "text",
    placeholder: "Dirección del paciente",
    name: "address",
    defaultValue: "",
  },
  phone: {
    required: false,
    label: "Celular",
    type: "number",
    placeholder: "Teléfono del paciente",
    name: "phone",
    defaultValue: "",
  },
  email: {
    required: false,
    label: "Email",
    type: "email",
    placeholder: "Email del paciente",
    name: "email",
    defaultValue: "",
  },
  emergencyContact: {
    required: false,
    label: "Contacto de Emergencia",
    type: "text",
    placeholder: "Nombre y Nro. Celular",
    name: "emergencyContact",
    defaultValue: "",
  },
  emergencyPhone: {
    required: false,
    label: "Celular de Emergencia",
    type: "number",
    placeholder: "Nro. de Celular de emergencia",
    name: "emergencyPhone",
    defaultValue: "",
  },
  healthInsurance: {
    required: false,
    label: "Seguro de Salud",
    type: "text",
    placeholder: "Seguro de salud del paciente",
    name: "healthInsurance",
    defaultValue: "",
  },
  maritalStatus: {
    required: false,
    label: "Estado Civil",
    type: "text",
    placeholder: "Estado civil del paciente",
    name: "maritalStatus",
    defaultValue: "",
  },
  occupation: {
    required: false,
    label: "Ocupación",
    type: "text",
    placeholder: "Ocupación del paciente",
    name: "occupation",
    defaultValue: "",
  },
  workplace: {
    required: false,
    label: "Lugar de Trabajo",
    type: "text",
    placeholder: "Lugar de trabajo del paciente",
    name: "workplace",
    defaultValue: "",
  },
  bloodType: {
    required: false,
    label: "Tipo de Sangre",
    type: "text",
    placeholder: "Tipo de sangre del paciente",
    name: "bloodType",
    defaultValue: "",
  },
  primaryDoctor: {
    required: false,
    label: "Médico de Cabecera",
    type: "text",
    placeholder: "Nombre y Nro. Celular",
    name: "primaryDoctor",
    defaultValue: "",
  },
  language: {
    required: false,
    label: "Idioma",
    type: "text",
    placeholder: "Idioma del paciente",
    name: "language",
    defaultValue: "",
  },
  notes: {
    required: false,
    label: "Notas",
    type: "text",
    placeholder: "Notas adicionales",
    name: "notes",
    defaultValue: "",
  },
  patientPhoto: {
    required: false,
    label: "Foto del Paciente",
    type: "file",
    placeholder: "URL de la foto del paciente",
    name: "patientPhoto",
    defaultValue: "",
  },

};


export const UPDATEFORMSTATICS: FormStatics<UpdatePatientInput> = {
  image: {
    required: false,
    label: "Imagen",
    type: "file",
    placeholder: "Seleccione una imagen",
    name: "image",
    defaultValue: "",
  },
  name: {
    required: false,
    label: "Nombre",
    type: "text",
    placeholder: "Nombre del paciente",
    name: "name",
    defaultValue: "",

  },
  lastName: {
    required: false,
    label: "Apellido",
    type: "text",
    placeholder: "Apellido del paciente",
    name: "lastName",
    defaultValue: "",
  },
  dni: {
    required: false,
    label: "DNI",
    type: "text",
    placeholder: "DNI del paciente",
    name: "dni",
    defaultValue: "",
  },
  birthDate: {
    required: false,
    label: "Fecha de Nacimiento",
    type: "date",
    placeholder: "Fecha de nacimiento del paciente",
    name: "birthDate",
    defaultValue: "",
  },
  gender: {
    required: false,
    label: "Género",
    type: "text",
    placeholder: "Género del paciente",
    name: "gender",
    defaultValue: "",
  },
  address: {
    required: false,
    label: "Dirección",
    type: "text",
    placeholder: "Dirección del paciente",
    name: "address",
    defaultValue: "",
  },
  phone: {
    required: false,
    label: "Celular",
    type: "text",
    placeholder: "Teléfono del paciente",
    name: "phone",
    defaultValue: "",
  },
  email: {
    required: false,
    label: "Email",
    type: "email",
    placeholder: "Email del paciente",
    name: "email",
    defaultValue: "",
  },
  emergencyContact: {
    required: false,
    label: "Contacto de Emergencia",
    type: "text",
    placeholder: "Nombre del contacto de emergencia",
    name: "emergencyContact",
    defaultValue: "",
  },
  emergencyPhone: {
    required: false,
    label: "Teléfono de Emergencia",
    type: "text",
    placeholder: "Teléfono del contacto de emergencia",
    name: "emergencyPhone",
    defaultValue: "",
  },
  healthInsurance: {
    required: false,
    label: "Seguro de Salud",
    type: "text",
    placeholder: "Seguro de salud del paciente",
    name: "healthInsurance",
    defaultValue: "",
  },
  maritalStatus: {
    required: false,
    label: "Estado Civil",
    type: "text",
    placeholder: "Estado civil del paciente",
    name: "maritalStatus",
    defaultValue: "",
  },
  occupation: {
    required: false,
    label: "Ocupación",
    type: "text",
    placeholder: "Ocupación del paciente",
    name: "occupation",
    defaultValue: "",
  },
  workplace: {
    required: false,
    label: "Lugar de Trabajo",
    type: "text",
    placeholder: "Lugar de trabajo del paciente",
    name: "workplace",
    defaultValue: "",
  },
  bloodType: {
    required: false,
    label: "Tipo de Sangre",
    type: "text",
    placeholder: "Tipo de sangre del paciente",
    name: "bloodType",
    defaultValue: "",
  },
  primaryDoctor: {
    required: false,
    label: "Médico Principal",
    type: "text",
    placeholder: "Nombre del médico principal",
    name: "primaryDoctor",
    defaultValue: "",
  },
  language: {
    required: false,
    label: "Idioma",
    type: "text",
    placeholder: "Idioma del paciente",
    name: "language",
    defaultValue: "",
  },
  notes: {
    required: false,
    label: "Notas",
    type: "text",
    placeholder: "Notas adicionales",
    name: "notes",
    defaultValue: "",
  },
  patientPhoto: {
    required: false,
    label: "Foto del Paciente",
    type: "text",
    placeholder: "URL de la foto del paciente",
    name: "patientPhoto",
    defaultValue: "",
  },

};
