name: Build Docker Image

on:
  push:
    branches: [staging-acide]
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: 'staging'
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Save GitHub SHA for deployment
        run: echo ${{ github.sha }} > github-sha.txt

      - name: Upload GitHub SHA as artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-sha
          path: github-sha.txt
          retention-days: 1

      - name: Validate environment variables
        run: |
          if [ -z "${{ vars.PROJECT_NAME }}" ]; then
            echo "Error: PROJECT_NAME must be defined in environment variables"
            exit 1
          fi
          if [ -z "${{ vars.SERVICE_TYPE }}" ]; then
            echo "Error: SERVICE_TYPE must be defined in environment variables"
            exit 1
          fi
          if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then
            echo "Error: DOCKERHUB_USERNAME must be defined in environment variables"
            exit 1
          fi
          if [ -z "${{ vars.DOCKERHUB_TOKEN }}" ]; then
            echo "Error: DOCKERHUB_TOKEN must be defined in environment variables"
            exit 1
          fi

      - name: Set environment variables
        run: |
          # Construir el nombre base del servicio
          BASE_NAME="${{ vars.SERVICE_TYPE }}-${{ vars.PROJECT_NAME }}"

          # Configurar variables para staging-acide
          echo "SERVICE_NAME=${BASE_NAME}-stage" >> "${GITHUB_ENV}"
          echo "ENV_TAG=stage" >> "${GITHUB_ENV}"
          echo "ENVIRONMENT_SUFFIX=-staging" >> "${GITHUB_ENV}"

          # Configurar nombre del repo para Docker
          echo "REPO_NAME=${BASE_NAME}${ENVIRONMENT_SUFFIX}" >> "${GITHUB_ENV}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            ${{ vars.SERVICE_TYPE == 'front' && format('BACKEND_URL={0}', vars.BACKEND_URL) || '' }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest-${{ env.ENV_TAG }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest-${{ env.ENV_TAG }}
          cache-to: type=inline
          provenance: false
          sbom: false 